"""
Crawler HTML Exporter

Professional HTML Report
"""

from __future__ import annotations

from pathlib import Path

from ..models import (
    CrawlStatistics,
    Page,
)


class HtmlExporter:
    """
    Export crawl results as a professional HTML report.
    """

    def export(
        self,
        target: str,
        pages: list[Page],
        statistics: CrawlStatistics,
    ) -> str:

        output_dir = Path("output/crawler")

        output_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        filename = (
            target.replace("https://", "")
            .replace("http://", "")
            .replace("/", "_")
        )

        output_file = output_dir / f"{filename}.html"

        total_scripts = sum(len(p.scripts) for p in pages)
        total_images = sum(len(p.images) for p in pages)
        total_css = sum(len(p.stylesheets) for p in pages)
        total_iframes = sum(len(p.iframes) for p in pages)
        total_forms = sum(len(p.forms) for p in pages)

        html = f"""
<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8">

<title>ReconForge Crawl Report</title>

<style>

body{{
background:#f3f5f7;
font-family:Segoe UI,Arial,sans-serif;
margin:40px;
}}

h1{{
margin:0;
}}

.header{{
background:#20232a;
color:white;
padding:25px;
border-radius:8px;
}}

.cards{{
display:flex;
gap:20px;
margin-top:25px;
margin-bottom:25px;
flex-wrap:wrap;
}}

.card{{
background:white;
padding:20px;
border-radius:8px;
box-shadow:0 1px 5px rgba(0,0,0,.15);
min-width:180px;
}}

.card h2{{
margin:0;
font-size:30px;
}}

.card p{{
margin-top:5px;
color:#666;
}}

table{{
width:100%;
border-collapse:collapse;
background:white;
box-shadow:0 1px 5px rgba(0,0,0,.15);
}}

th{{
background:#2d3748;
color:white;
padding:12px;
}}

td{{
padding:10px;
border-bottom:1px solid #eee;
font-size:14px;
}}

tr:nth-child(even){{
background:#fafafa;
}}

.badge200{{
background:#16a34a;
color:white;
padding:4px 8px;
border-radius:4px;
}}

.badge300{{
background:#2563eb;
color:white;
padding:4px 8px;
border-radius:4px;
}}

.badge400{{
background:#dc2626;
color:white;
padding:4px 8px;
border-radius:4px;
}}

.badge500{{
background:#7f1d1d;
color:white;
padding:4px 8px;
border-radius:4px;
}}

a{{
color:#2563eb;
text-decoration:none;
}}

.footer{{
margin-top:30px;
text-align:center;
color:#888;
}}

</style>

</head>

<body>

<div class="header">

<h1>ReconForge Web Crawl Report</h1>

<p><b>Target:</b> {target}</p>

</div>

<div class="cards">

<div class="card">
<h2>{statistics.pages_crawled}</h2>
<p>Pages</p>
</div>

<div class="card">
<h2>{statistics.links_discovered}</h2>
<p>Links</p>
</div>

<div class="card">
<h2>{total_scripts}</h2>
<p>Scripts</p>
</div>

<div class="card">
<h2>{total_images}</h2>
<p>Images</p>
</div>

<div class="card">
<h2>{total_forms}</h2>
<p>Forms</p>
</div>

<div class="card">
<h2>{total_css}</h2>
<p>CSS Files</p>
</div>

<div class="card">
<h2>{total_iframes}</h2>
<p>Iframes</p>
</div>

</div>

<table>

<tr>

<th>Status</th>
<th>Depth</th>
<th>Title</th>
<th>URL</th>
<th>Links</th>
<th>Scripts</th>
<th>Images</th>
<th>CSS</th>
<th>Forms</th>

</tr>
"""

        for page in pages:

            if page.status < 300:
                badge = "badge200"
            elif page.status < 400:
                badge = "badge300"
            elif page.status < 500:
                badge = "badge400"
            else:
                badge = "badge500"

            html += f"""

<tr>

<td><span class="{badge}">{page.status}</span></td>

<td>{page.depth}</td>

<td>{page.title}</td>

<td><a href="{page.url}" target="_blank">{page.url}</a></td>

<td>{len(page.links)}</td>

<td>{len(page.scripts)}</td>

<td>{len(page.images)}</td>

<td>{len(page.stylesheets)}</td>

<td>{len(page.forms)}</td>

</tr>

"""

        html += """

</table>

<div class="footer">

Generated by ReconForge Web Crawler

</div>

</body>

</html>

"""

        output_file.write_text(
            html,
            encoding="utf-8",
        )

        return str(output_file)


html_exporter = HtmlExporter()